#ifndef _TESTING_SPEC_
#define _TESTING_SPEC_

#define SPEC_TABLE              SpecTable
#define SPEC_INDEX              4048
#define SPEC_NAME               "BF"
#define PROD_NAME               "BF126"
#define BUILD_ORDER             99999
#define REEL                    999999
#define TINDEX                  898989

#define OPERATING_VOLTAGE       2.5
#define SLAVE_ADDRESS           "00011111" // 0x1F

#define DEFAULT_IMAGE           \
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
#define DEFAULT_MASK            \
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"

#define SPEC_ACCEL_MAXCOUNT               65536

#endif
